\i pais.sql
\i usuario.sql
\i ciudad.sql
\i servicio.sql
\i reserva.sql
\i transaccion.sql
\i transaccion_estado.sql
\i guia.sql
\i agencia.sql
\i destino.sql
\i rutas.sql
\i rutas_destinos.sql
\i viaje.sql
\i viajes_rutas.sql
\i guias_rutas.sql